// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubclassesTracker.Database.Context;

#nullable disable

namespace SubclassesTracker.Database.Migrations.ParquetCache
{
    [DbContext(typeof(ParquetCacheContext))]
    partial class ParquetCacheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileEntryRequestSnapshot", b =>
                {
                    b.Property<int>("FileEntriesId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestSnapshotsId")
                        .HasColumnType("integer");

                    b.HasKey("FileEntriesId", "RequestSnapshotsId");

                    b.HasIndex("RequestSnapshotsId");

                    b.ToTable("FileEntryRequestSnapshot");
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.FileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PartitionId")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<long>("Ttl")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("PartitionId");

                    b.ToTable("FileEntries");
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.Partition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("Partitions");
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.RequestSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QueryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VarsHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VarsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QueryName", "VarsHash")
                        .IsUnique();

                    b.ToTable("RequestSnapshots");
                });

            modelBuilder.Entity("FileEntryRequestSnapshot", b =>
                {
                    b.HasOne("SubclassesTracker.Database.CacheEntities.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("FileEntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubclassesTracker.Database.CacheEntities.RequestSnapshot", null)
                        .WithMany()
                        .HasForeignKey("RequestSnapshotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.FileEntry", b =>
                {
                    b.HasOne("SubclassesTracker.Database.CacheEntities.Dataset", "Dataset")
                        .WithMany("Files")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubclassesTracker.Database.CacheEntities.Partition", "Partition")
                        .WithMany("Files")
                        .HasForeignKey("PartitionId");

                    b.Navigation("Dataset");

                    b.Navigation("Partition");
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.Partition", b =>
                {
                    b.HasOne("SubclassesTracker.Database.CacheEntities.Dataset", "Dataset")
                        .WithMany("Partitions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.Dataset", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Partitions");
                });

            modelBuilder.Entity("SubclassesTracker.Database.CacheEntities.Partition", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
