name: Build and Deploy

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SubclassesTrackerExtension.sln
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: dotnet publish SubclassesTracker.Api.csproj -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SubclassesTracker.Api
          path: publish
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH connection
        run: |
          echo "${{ secrets.YOKO_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -vvv -i key.pem -o StrictHostKeyChecking=no ${{ secrets.YOKO_USER }}@${{ secrets.YOKO_HOST }} exit
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to yokocodev.site
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.YOKO_HOST }}
          username: ${{ secrets.YOKO_USER }}
          key: ${{ secrets.YOKO_KEY }}
          target: ${{ secrets.YOKO_TARGET }}
          source: "publish/*"
